site:
  title: "Крутой Зоопарк"
  description: "Самый смешной зоопарк в мире!"
  contact_info: 
    email: "funnyzoo@example.com"
    phone: "хуй"
animals:
  - name: "Летающий Слон"
    description: "Легче воздуха и обожает воздушные шоу."
  - name: "Невидимый Тигр"
    description: "Его никто не видел, но из его клетки еще никто не возвращался!"
  - name: "Громогласный Утконос"
    description: "Слышен за километр. Имеет страсть к написанию реп альбомой."
